Upload guide
iwmihq/miniSASS pull request #1000
Opened 2024-04-23 07:02 UTC by ketankartoza

This PR is for the issue #996

2024-04-23 07:41 UTC, Jeremy-Prior requested changes

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +By default the create new site option is selected. Fill the 1️⃣ required filds and upload the image of the site. To upload the image of the site click on the 2️⃣ `Upload site images` button.
```suggestion
By default the create new site option is selected. Fill the 1️⃣ required fields and upload the image of the site. To upload the image of the site click on the 2️⃣ `Upload site images` button.
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +Select this option by clickng on the 1️⃣ `Use Existing Site` radio button.
```suggestion
Select this option by clicking on the 1️⃣ `Use Existing Site` radio button.
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +In this option you can enter the coordinates manually via two different types. You can either enter DMS coorrdinates or degree coordinate.
```suggestion
In this option you can enter the coordinates manually via two different types. You can either enter DMS coordinates or degree coordinate.
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +To enter the DMS coordinates click on the redio button available in front of the DMS.
```suggestion
To enter the DMS coordinates click on the radio button available in front of the DMS.
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +Enter the collectors name and the notes in the 1️⃣ available fields and select the 2️⃣ date from the calander.
```suggestion
Enter the collectors name and the notes in the 1️⃣ available fields and select the 2️⃣ date from the calendar.
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +Enter the measurment details in the 1️⃣ available fields. and the click on the
```suggestion
Enter the measurement details in the 1️⃣ available fields and the click on the next button
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +![measurment](./img/upload-16.png)
```suggestion
![measurement](./img/upload-16.png)
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +![measurment](./img/upload-17.png)
```suggestion
![measurement](./img/upload-17.png)
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +Upon clicking the next button the score form will open. Where you can select the group by clicking on the checkbox available in front of the group name and upload the images by clickin on the `Upload
```suggestion
Upon clicking the next button the score form will open. Where you can select the group by clicking on the checkbox available in front of the group name and upload the images by clicking on the `Upload images` button available after the name of the group.
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +Upon clicking on this button the add record form will open. This form have four sections
```suggestion
Upon clicking on this button the add record form will open. This form has four sections
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +![observation ditails](./img/upload-14.png)
```suggestion
![observation details](./img/upload-14.png)
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +>Note: If the `Next` button is not clickable and the incomplete form message (Incomplete form. Please scroll up to complete the highlighted fields.) shown on the form that means you have forgotten to
```suggestion
>Note: If the `Next` button is not clickable and the incomplete form message (Incomplete form. Please scroll up to complete the highlighted fields.) is shown on the form that means you have forgotten to fill the required fields.
```

2024-04-23 07:41 UTC, Jeremy-Prior commented on docs/src/user/guide/upload.md
> +Fill all the required fields to proceed further. After filling all the required fields the incomplete form message will not show on the page and the `Next` button will be clickable. Click on the 1️⃣
```suggestion
Fill all of the required fields to proceed further. After filling all the required fields the incomplete form message will not show on the page and the `Next` button will be clickable. Click on the 1️⃣ next button for next step of data uploading.
```

2024-04-23 14:32 UTC, Jeremy-Prior approved these changes
LGTM

2024-04-23 14:32 UTC, Jeremy-Prior commented
@ketankartoza please address the merge conflicts when possible.

2024-05-02 11:54 UTC, merged

2024-05-02 11:57 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 24 sec