Update logout manual
iwmihq/miniSASS pull request #1002
Opened 2024-04-24 08:14 UTC by ketankartoza

This PR is for the issue #1001

2024-04-24 12:57 UTC, Jeremy-Prior requested changes

2024-04-24 12:57 UTC, Jeremy-Prior commented on docs/src/user/manual/register/register.md
> +On successful submition the success message will be shown.
```suggestion
On successful submission the success message will be shown.
```

2024-05-02 11:55 UTC, Jeremy-Prior approved these changes

2024-05-02 11:55 UTC, merged

2024-05-02 11:59 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 56 sec