Map guide
iwmihq/miniSASS pull request #1004
Opened 2024-04-24 13:45 UTC by ketankartoza

This PR is for the issue #999

2024-04-24 14:17 UTC, Jeremy-Prior requested changes
Spelling was good, just some minor language adjustments.

2024-04-24 14:17 UTC, Jeremy-Prior commented on docs/src/user/guide/map.md
> +Upon clicking, the legend will be hidden.
```suggestion
Upon clicking the icon, the legend will be hidden.
```

2024-04-24 14:17 UTC, Jeremy-Prior commented on docs/src/user/guide/map.md
> +You can search for the desired site on the map by typing into the 1️⃣ search bar located at the top right corner.
```suggestion
You can search for the desired site on the map by typing into the 1️⃣ search bar located in the top right corner.
```

2024-04-24 14:17 UTC, Jeremy-Prior commented on docs/src/user/guide/map.md
> +Upon clicking the popup will open, where you can select the layer. To select the `Satellite` layer click on the 1️⃣ radio button available in front of the satellite.
```suggestion
Upon clicking the icon, the popup will open, where you can select the layer. To select the `Satellite` layer click on the 1️⃣ radio button available in front of the satellite.
```

2024-05-02 12:09 UTC, Jeremy-Prior approved these changes

2024-05-02 12:10 UTC, Jeremy-Prior commented
@ketankartoza Please address the conflicts when possible

2024-05-02 12:39 UTC, merged

2024-05-02 12:40 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 38 sec