feat: create fetch sites data api view
iwmihq/miniSASS pull request #1050
Opened 2024-06-18 08:07 UTC by tinashechiraya

2024-06-18 12:54 UTC, dimasciput commented on django_project/monitor/site_views.py
> +		start_date = parse_date(start_date_str) if start_date_str else None
What happens if the parsing fails? Maybe add error handling here. If it fails, then just return a 400 instead of returning all sites.

2024-06-18 12:54 UTC, dimasciput requested changes
@tinashechiraya please check my comment

2024-06-18 17:28 UTC, tinashechiraya commented on django_project/monitor/site_views.py
> +		start_date = parse_date(start_date_str) if start_date_str else None
I have resolved this and added error handling mechanisms

2024-06-24 10:14 UTC, dimasciput approved these changes

2024-06-24 10:14 UTC, merged

2024-06-24 10:25 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 10 min