patch: create seperate serializers for sites and observations
iwmihq/miniSASS pull request #1058
Opened 2024-07-23 06:54 UTC by tinashechiraya

The existing serializers return combined data for sites and observations as this is the expected result on the frontend however for this API the data requires a better structure which is why i have created these additional serialzers so that the output structure matches the one requested by the client

![sites_with_observations_api](https://github.com/user-attachments/assets/2f5e47e3-0874-436b-9060-f637323e080f)

example usage: '/sites-with-observations/?start_date=2023-03-13'

2024-07-23 16:07 UTC, dimasciput requested changes

2024-07-23 16:07 UTC, dimasciput commented on django_project/monitor/serializers.py
> +		model = Observations
@tinashechiraya can you check the spacing, it looks different with the existing codes.

2024-07-31 07:54 UTC, dimasciput approved these changes

2024-07-31 07:54 UTC, merged

2024-07-31 08:11 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 16 min