update python and django version
iwmihq/miniSASS pull request #228
Opened 2023-11-20 08:01 UTC by tinashechiraya

2023-11-20 08:08 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 42 sec

2023-11-20 08:41 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 21 sec

2023-11-20 09:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 25 sec

2023-11-20 12:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 54 sec

2023-11-20 12:49 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 13 sec

2023-11-20 14:37 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 21 sec

2023-11-20 14:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 28 sec

2023-11-20 14:44 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 29 sec

2023-11-20 16:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 20 sec

2023-11-20 16:50 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 43 sec

2023-11-20 16:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 20 sec

2023-11-20 16:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 38 sec

2023-11-21 02:04 UTC, dimasciput requested changes

2023-11-21 02:04 UTC, dimasciput commented on django_project/minisass/settings.py
> +# EMAIL_HOST = os.getenv('SMTP_HOST')
@tinashechiraya why do you commented these? you can use `os.environ.get('SMTP_HOST', '')` instead.

2023-11-21 05:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 55 sec

2023-11-22 00:04 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 6 sec

2023-11-22 00:06 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 30 sec

2023-11-22 01:11 UTC, dimasciput approved these changes

2023-11-22 01:11 UTC, merged

2023-11-22 01:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 43 sec