Observations api
iwmihq/miniSASS pull request #263
Opened 2023-11-22 23:50 UTC by tinashechiraya

Description:

I have fixed the gis/openlayers.html templates missing in django admin thereby preventing a user from creating a site

The observations now have a view to:
fetch all observations
fetch recent observations for the home page
fetch observation by id 
fetch observation by site id
create observation

clicking on an observation on the home page will now fetch the additional observation details which the user can see on the observation form on the map

still todo 
- [ ] populate the score form with observation data from api
- [ ] zoom to location on map when observation is clicked from home page 
I will do these in a seperate pr

2023-11-22 23:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 3 min 37 sec

2023-11-23 00:03 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 4 sec

2023-11-23 01:27 UTC, dimasciput commented
@tinashechiraya please add screenshot or a video

2023-11-23 06:14 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 50 sec

2023-11-23 06:58 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 6 sec

2023-11-23 21:44 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 37 sec

2023-11-23 21:49 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 47 sec

2023-11-23 21:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 17 sec

2023-11-23 22:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 46 sec

2023-11-23 22:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 21 sec

2023-11-23 22:31 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 3 sec

2023-11-23 23:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 2 sec

2023-11-23 23:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 4 sec

2023-11-23 23:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 6 sec

2023-11-23 23:47 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 10 sec

2023-11-23 23:49 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 47 sec

2023-11-24 00:02 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 27 sec

2023-11-24 00:04 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 45 sec

2023-11-24 06:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 23 sec

2023-11-24 06:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 19 sec

2023-11-24 07:13 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 16 sec

2023-11-24 08:00 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 7 min 52 sec

2023-11-24 08:02 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 43 sec

2023-11-24 08:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 54 sec

2023-11-24 08:26 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 38 sec

2023-11-24 08:41 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 51 sec

2023-11-24 11:11 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 59 sec

2023-11-24 11:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 36 sec

2023-11-24 11:22 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 3 sec

2023-11-24 11:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 5 sec

2023-11-24 11:30 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 13 sec

2023-11-24 11:56 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 25 sec

2023-11-24 12:19 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 47 sec

2023-11-24 12:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 59 sec

2023-11-24 13:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 38 sec

2023-11-24 13:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 31 sec

2023-11-24 13:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 43 sec

2023-11-24 13:37 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 17 sec

2023-11-24 13:39 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 51 sec

2023-11-24 13:59 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 19 sec

2023-11-24 14:01 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 1 sec

2023-11-24 14:20 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 31 sec

2023-11-27 04:42 UTC, dimasciput requested changes
@tinashechiraya please add tests for the observation api in this PR

2023-11-27 04:42 UTC, dimasciput commented on django_project/monitor/observation_views.py
> +            recent_observations.append({
@tinashechiraya please use serializer

2023-11-27 04:42 UTC, dimasciput commented on django_project/monitor/observation_views.py
> +            observation_data = {
@tinashechiraya please use serializer

2023-11-28 05:00 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 23 sec

2023-11-28 05:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 59 sec

2023-11-28 05:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 4 sec

2023-11-28 05:12 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 19 sec

2023-11-28 05:15 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 2 sec

2023-11-28 05:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 34 sec

2023-11-28 05:19 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 24 sec

2023-11-28 06:21 UTC, dimasciput commented on django_project/monitor/urls.py
> +    path('observations-old/<int:site_id>/', get_observations),
```suggestion
    path('legacy/observation/<int:obs_id>/', zoom_observation),
    path('legacy/observations/<int:site_id>/', get_observations),
```

2023-11-28 06:21 UTC, dimasciput approved these changes

2023-11-28 06:22 UTC, merged

2023-11-28 06:26 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 22 sec

2023-11-28 06:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 44 sec