Sites api documentation
iwmihq/miniSASS pull request #323
Opened 2023-12-01 12:47 UTC by tinashechiraya

Description:

Documentation on how to use the sites api

2023-12-01 12:49 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 50 sec

2023-12-05 06:53 UTC, Jeremy-Prior requested changes
Minor changes

2023-12-05 06:53 UTC, Jeremy-Prior commented on docs/src/developer/sites.md
> +- `time_stamp`: Optional field ,if not provided current datetime is added to the site
```suggestion
- `time_stamp`: Optional field, if not provided current datetime is added to the site
```

2023-12-05 06:53 UTC, Jeremy-Prior commented on docs/src/developer/sites.md
> +any field can be updated on the site
```suggestion
Any field can be updated on the site
```

2023-12-05 07:25 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 9 sec

2023-12-05 07:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 18 sec

2023-12-05 07:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 5 sec

2023-12-05 10:13 UTC, Jeremy-Prior approved these changes
LGTM

2023-12-05 11:31 UTC, merged

2023-12-05 11:34 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 46 sec