UI fixes 3
iwmihq/miniSASS pull request #360
Opened 2023-12-06 11:17 UTC by tinashechiraya

https://github.com/kartoza/miniSASS/assets/70011086/d9a54ba1-fc3e-4296-901c-2262bd8ce775

![contact_back](https://github.com/kartoza/miniSASS/assets/70011086/f9fd3048-5bfc-45b5-a685-3a25ba318dc0)

![completed_reg](https://github.com/kartoza/miniSASS/assets/70011086/7a2a2a4d-c8bc-42c3-8ffd-e347c5b6b791)

Description:
when the site is not ready a loading bar will appear
I have also moved the success message from the contact us form to appear on its own because it overlapping the fields in the form
I have also updated the completed registration modal styling so it matches the universal theme for the website

2023-12-06 11:23 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 48 sec

2023-12-07 01:24 UTC, dimasciput approved these changes

2023-12-07 01:26 UTC, dimasciput requested changes

2023-12-07 01:26 UTC, dimasciput commented on django_project/minisass_frontend/src/components/ContactFormModal/index.tsx
> +  const [MessageSent, setMessageSent] = useState(false);
```suggestion
  const [sendingMessage, setSendingMessage] = useState(false);
  const [messageSent, setMessageSent] = useState(false);
```

2023-12-07 01:26 UTC, dimasciput commented on django_project/minisass_frontend/src/components/ContactFormModal/index.tsx
> +      ) : MessageSent ? (
```suggestion
      {sendingMessage ? (
        <LinearProgress color="success" />
      ) : messageSent ? (
```

2023-12-07 06:16 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 55 sec

2023-12-07 06:18 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 17 sec

2023-12-07 07:52 UTC, merged

2023-12-07 07:57 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 16 sec