Update sites model
iwmihq/miniSASS pull request #364
Opened 2023-12-06 13:46 UTC by tinashechiraya

Description:

I have updated the sites model with additional fields required by Rico issue #333
I have also created the models that will be linked to a site

2023-12-06 13:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 59 sec

2023-12-07 01:21 UTC, dimasciput requested changes

2023-12-07 01:21 UTC, dimasciput commented on django_project/monitor/models.py
> +    assessment_id = models.ForeignKey(Assessment, on_delete=models.CASCADE,blank=True,null=True)
@tinashechiraya, we don't need to add the suffix '_id' to the field, as it will be added automatically.

2023-12-07 01:21 UTC, dimasciput commented on django_project/monitor/models.py
> +    miniSass_score = models.FloatField(blank=True,null=True)
```suggestion
    minisass_score = models.FloatField(blank=True,null=True)
```

2023-12-07 01:21 UTC, dimasciput commented on django_project/monitor/models.py
> +    miniSass_ML_score = models.FloatField(blank=True,null=True)
```suggestion
    minisass_ML_score = models.FloatField(blank=True,null=True)
```

Please avoid using camelcase in strings for Python scripts.

2023-12-07 01:21 UTC, dimasciput commented on django_project/monitor/models.py
> +    image_id = models.AutoField(primary_key=True)
@tinashechiraya why do we need _id_ field? I think this will be automatically generated in new django.

2023-12-07 01:21 UTC, dimasciput commented on django_project/minisass/migrations/0002_groupscores.py
Don't remove this.

2023-12-07 01:21 UTC, dimasciput commented on django_project/minisass/migrations/0003_alter_groupscores_id.py
Please don't remove this.

2023-12-07 01:21 UTC, dimasciput commented on django_project/minisass/migrations/0003_alter_groupscores_id.py
Let's not worry about the dev version for now.

2023-12-07 01:29 UTC, dimasciput commented on django_project/monitor/models.py
> +# TODO this will be for Irwan for image uploads
```suggestion
```

2023-12-07 06:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 6 min 8 sec

2023-12-07 06:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 33 sec

2023-12-07 06:28 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 15 sec

2023-12-08 11:23 UTC, tinashechiraya commented
move 
ml score ,type and version to observations model

2023-12-09 07:46 UTC, closed without merging

2023-12-09 07:52 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 5 sec