Update observation docs
iwmihq/miniSASS pull request #383
Opened 2023-12-08 13:27 UTC by tinashechiraya

2023-12-08 13:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 3 sec

2023-12-11 06:40 UTC, Jeremy-Prior requested changes

2023-12-11 06:40 UTC, Jeremy-Prior commented on docs/src/developer/observations.md
> +2. For attaching images to pests/groups (e.g., flatworms, stoneflies, other_mayflies), the variable should be named `"pest_0:name_of_pest"`. The value should be the binary file (image), and the corre
```suggestion
2. For attaching images to pests/groups (e.g. flatworms, stoneflies, other_mayflies), the variable should be named `"pest_0:name_of_pest"`. The value should be the binary file (image), and the corresponding pest/group must be set to `true`.
```

2023-12-11 07:46 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 30 sec

2023-12-11 14:12 UTC, Jeremy-Prior approved these changes
LGTM

2023-12-12 07:51 UTC, merged

2023-12-12 07:55 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 2 min 34 sec