Direct submit results to map page
iwmihq/miniSASS pull request #444
Opened 2023-12-14 22:30 UTC by tinashechiraya

https://github.com/kartoza/miniSASS/assets/70011086/e4bf3fd1-3869-4cf9-bbcd-397dd350acf3

Description
clicking on submit results now navigates to the map page and opens the add record form

2023-12-14 22:35 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 5 min 1 sec

2023-12-15 00:18 UTC, NyakudyaA requested changes
It's behaving differently to the Add record. When a user is not logged in, it should ask for login then open the form when logged in

@NyakudyaA don't worry it will behave as expected its just on my localhost i disabled logging in

2023-12-15 01:14 UTC, NyakudyaA approved these changes

2023-12-15 01:15 UTC, merged

2023-12-15 01:21 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 4 min 51 sec