Manual use existing site
iwmihq/miniSASS pull request #573
Opened 2024-01-04 13:39 UTC by ketankartoza

This PR is for issue #563

@NyakudyaA, please note that the latest documentation is available in this branch. You can directly merge this branch, as it already incorporates the content from PR #538 and #545.

2024-01-04 13:41 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 32 sec

2024-01-05 08:38 UTC, Jeremy-Prior requested changes

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/map/map.md
> +2. **United Nations Children's Fund (UNICEF)**: UNICEF works in over 190 countries and territories to save children's lives, defend their rights, and help them fulfill their potential, from early chi
```suggestion
2. **United Nations Children's Fund (UNICEF)**: UNICEF works in over 190 countries and territories to save children's lives, defend their rights, and help them fulfil their potential, from early childhood through adolescence. And we never give up.
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/map/map.md
> +# Map Page After Login User Manual
```suggestion
## Map Page After Login User Manual
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/map/map.md
> +## Available References
```suggestion
### Available References
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/map/map.md
> +2. **United Nations Children's Fund (UNICEF)**: UNICEF works in over 190 countries and territories to save children's lives, defend their rights, and help them fulfill their potential, from early chi
```suggestion
2. **United Nations Children's Fund (UNICEF)**: UNICEF works in over 190 countries and territories to save children's lives, defend their rights, and help them fulfil their potential, from early childhood through adolescence. And we never give up.
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/map/map.md
> +## Footer Options
```suggestion
### Footer Options
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +    ### Site Details Section
Headings shouldn't be indented in markdown
```suggestion
    **Site Details Section**
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +        #### Upload Image
```suggestion
        **Upload Image**
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +    ### Site Location section
```suggestion
    **Site Location section**
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +        a. **Water Clarity (cm):** Enter the water clarity measurement in centimeters.
```suggestion
        a. **Water Clarity (cm):** Enter the water clarity measurement in centimetres.
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +            mg/l (milligrams per liter)
```suggestion
            mg/l (milligrams per litre)
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +            µS/cm (microsiemens per centimeter)
```suggestion
            µS/cm (microsiemens per centimetre)
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +    ### Site Details Section
```suggestion
    **Site Details Section**
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +        #### Upload Image
```suggestion
        **Upload Image**
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +    ### Site Location section
```suggestion
    **Site Location section**
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +        a. **Water Clarity (cm):** Enter the water clarity measurement in centimeters.
```suggestion
        a. **Water Clarity (cm):** Enter the water clarity measurement in centimetres.
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +            mg/l (milligrams per liter)
```suggestion
            mg/l (milligrams per litre)
```

2024-01-05 08:38 UTC, Jeremy-Prior commented on docs/src/user/manual/upload/add-records.md
> +            µS/cm (microsiemens per centimeter)
```suggestion
            µS/cm (microsiemens per centimetre)
```

2024-01-05 11:27 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 27 sec

2024-01-05 12:24 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 23 sec

2024-01-08 08:28 UTC, Jeremy-Prior approved these changes
LGTM

2024-01-09 06:44 UTC, merged

2024-01-09 06:47 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 28 sec