Add doc for the recent observation
iwmihq/miniSASS pull request #587
Opened 2024-01-08 12:52 UTC by ketankartoza

This PR is for issue #578

2024-01-08 12:54 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 30 sec

2024-01-09 06:43 UTC, Jeremy-Prior requested changes

2024-01-09 06:43 UTC, Jeremy-Prior commented on docs/src/user/manual/map/recent-observation.md
> +3. **CGIAR**: CGIAR is a global research partnership for a food-secure future dedicated to transforming food, land, and water systems in a climate crisis.CGIAR is the world’s largest global agricultu
```suggestion
3. **CGIAR**: CGIAR is a global research partnership for a food-secure future dedicated to transforming food, land, and water systems in a climate crisis. CGIAR is the world’s largest global agricultural innovation network.
```

2024-01-09 06:43 UTC, Jeremy-Prior commented on docs/src/user/manual/map/recent-observation.md
> +## Introduction:
```suggestion
## Introduction:

```

2024-01-09 07:19 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** FAILURE
**Build duration:** 1 min 38 sec

2024-01-09 07:21 UTC, Jeremy-Prior approved these changes
LGTM

2024-01-09 07:22 UTC, merged

2024-01-09 07:23 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec