update site docs
iwmihq/miniSASS pull request #881
Opened 2024-02-05 08:36 UTC by tinashechiraya

2024-02-05 08:38 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 42 sec

2024-02-05 08:40 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 31 sec

2024-02-05 08:43 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 32 sec

2024-02-05 08:45 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 41 sec

2024-02-05 10:04 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 40 sec

2024-02-06 07:03 UTC, Jeremy-Prior requested changes

2024-02-06 07:03 UTC, Jeremy-Prior commented on docs/src/developer/observations.md
> +- `image_0`: these can be added from _0 to _10 or more. This is for attaching site images which will be retrived from the request object.
```suggestion
- `image_0`: these can be added from _0 to _10 or more. This is for attaching site images which will be retrieved from the request object.
```

2024-02-06 07:03 UTC, Jeremy-Prior commented on docs/src/developer/observations.md
> +- `siteId`: interger value provided create_site_or_observation is false.
```suggestion
- `siteId`: integer value provided create_site_or_observation is false.
```

2024-02-06 07:03 UTC, Jeremy-Prior commented on docs/src/developer/sites.md
> +  - HTTP_500_INTERNAL_SERVER_ERROR: provided image is invalid or something unexpected occured.
```suggestion
  - HTTP_500_INTERNAL_SERVER_ERROR: provided image is invalid or something unexpected occurred.
```

2024-02-06 07:03 UTC, Jeremy-Prior commented on docs/src/developer/sites.md
> +  - HTTP_400_BAD_REQUEST: invalid site id supplied (non integer ,unconvertable string char etc).
```suggestion
  - HTTP_400_BAD_REQUEST: invalid site id supplied (non integer, unconvertable string char etc).
```

2024-02-06 07:03 UTC, Jeremy-Prior commented on docs/src/developer/observations.md
> +    bugs or beetles: 10 (staging) , 23 (production)
```suggestion
    bugs or beetles: 10 (staging), 23 (production)
```

2024-02-06 07:03 UTC, Jeremy-Prior commented on docs/src/developer/observations.md
> +"observationdId": 1 , //the id of the observation to which the images will be attached
```suggestion
"observationdId": 1, //the id of the observation to which the images will be attached
```

2024-02-06 08:05 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 40 sec

2024-02-06 08:07 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 51 sec

2024-02-06 08:09 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 40 sec

2024-02-06 08:10 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 27 sec

2024-02-06 08:12 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 39 sec

2024-02-06 08:14 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 41 sec

2024-02-06 10:28 UTC, tinashechiraya commented
@Jeremy-Prior I have committed you suggestions. Thanks

2024-02-07 07:09 UTC, Jeremy-Prior approved these changes
LGTM

2024-02-07 07:09 UTC, merged

2024-02-07 07:29 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 36 sec