Add quckstart doc
iwmihq/miniSASS pull request #992
Opened 2024-04-18 05:12 UTC by ketankartoza

2024-04-19 14:01 UTC, Jeremy-Prior requested changes

2024-04-19 14:01 UTC, Jeremy-Prior commented on docs/src/user/quickstart/index.md
> +On successful submition you will see the registration in progress message. To complete the regstration process you need to activate your account￼.
```suggestion
On successful submission you will see the registration in progress message. To complete the registration process you need to activate your account￼.
```

2024-04-19 14:01 UTC, Jeremy-Prior commented on docs/src/user/quickstart/index.md
> +Go to your email and check the activation email for the account activation sended by the miniSASS.
```suggestion
Go to your email and check the activation email for the account activation sent by the miniSASS.
```

2024-04-19 14:01 UTC, Jeremy-Prior commented on docs/src/user/quickstart/index.md
> +You can use the `Retrieve Email Address` button, to retrieve the email addrese using your username in case you forgot your associate email address with the username.
```suggestion
You can use the `Retrieve Email Address` button, to retrieve the email address using your username in case you forgot your email address associated with the username.
```

2024-04-22 06:46 UTC, Jeremy-Prior approved these changes
LGTM

2024-04-22 06:47 UTC, merged

2024-04-22 06:48 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 51 sec