User guide doc
iwmihq/miniSASS pull request #993
Opened 2024-04-18 17:45 UTC by ketankartoza

This PR is for the issue #989

2024-04-19 14:01 UTC, Jeremy-Prior requested changes

2024-04-19 14:01 UTC, Jeremy-Prior commented on docs/src/user/guide/register-login-logout.md
> +On successful submition you will see the registration in progress message. To complete the regstration process you need to activate your account.
```suggestion
On successful submission you will see the registration in progress message. To complete the registration process you need to activate your account.
```

2024-04-19 14:01 UTC, Jeremy-Prior commented on docs/src/user/guide/register-login-logout.md
> +Go to your email and check the activation email for the account activation sended by the miniSASS.
```suggestion
Go to your email and check the activation email for the account activation sent by the miniSASS.
```

2024-04-19 14:01 UTC, Jeremy-Prior commented on docs/src/user/guide/register-login-logout.md
> +On the login page fill the email address and the password in the 1️⃣ corosponding fields. Once you have entered your email address and password, click on the 2️⃣ `Login` button to proceed.
```suggestion
On the login page fill the email address and the password in the 1️⃣ corresponding fields. Once you have entered your email address and password, click on the 2️⃣ `Login` button to proceed.
```

2024-04-22 07:02 UTC, Jeremy-Prior approved these changes
LGTM

2024-04-22 07:03 UTC, Jeremy-Prior commented
@ketankartoza please address the merge conflicts when possible

2024-04-22 08:11 UTC, merged

2024-04-22 08:13 UTC, lgkgh commented
#### Jenkins Build Details:
**Build status:** SUCCESS
**Build duration:** 1 min 54 sec